"""page geometry and citation precision

Adds the last two links of the provenance chain: where a page's words sit on the
rendered page, and how precisely a citation is pinned to them.

Additive by design. Existing rows keep their text and offsets untouched — the
defaults say "this page has characters but no layout" and "this citation has not
been graded yet", which is exactly what is true of them until
``scripts/backfill_provenance.py`` looks at each one and says something better.

Revision ID: 0bacb3a08722
Revises: 0f54265fcc7a
Create Date: 2026-08-15 01:32:30.398367
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types used by the models (exact-decimal Money) render as
# their fully qualified name, so the module has to be importable here.
import app.domain.money  # noqa: F401

revision: str = '0bacb3a08722'
down_revision: str | None = '0f54265fcc7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('extraction_method', sa.String(length=16), server_default='text', nullable=False))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('words', sa.JSON(), nullable=True))

    with op.batch_alter_table('fact_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citation_status', sa.String(length=16), server_default='UNRESOLVED', nullable=False))
        batch_op.add_column(sa.Column('bounding_boxes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_sources', schema=None) as batch_op:
        batch_op.drop_column('confidence')
        batch_op.drop_column('bounding_boxes')
        batch_op.drop_column('citation_status')

    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_column('words')
        batch_op.drop_column('word_count')
        batch_op.drop_column('extraction_method')
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
