"""demand generation metadata

Records where a draft's prose crossed an external boundary and what that
boundary reported: the AI boundary name, upstream provider/model, gateway
request ids, token usage, and the privacy summary of counts.

Nullable and additive. Demands generated before this column existed keep a NULL,
which is read as "no boundary metadata recorded" rather than "no boundary" — the
UI distinguishes the two.

Revision ID: 4051759fb9ba
Revises: 0bacb3a08722
Create Date: 2026-08-15 17:34:53.396344
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types used by the models (exact-decimal Money) render as
# their fully qualified name, so the module has to be importable here.
import app.domain.money  # noqa: F401

revision: str = '4051759fb9ba'
down_revision: str | None = '0bacb3a08722'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.drop_column('generation_metadata')

    # ### end Alembic commands ###
