"""initial schema

Revision ID: 0f54265fcc7a
Revises: 
Create Date: 2026-08-13 12:03:33.336688
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types used by the models (exact-decimal Money) render as
# their fully qualified name, so the module has to be importable here.
import app.domain.money  # noqa: F401

revision: str = '0f54265fcc7a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('demand_id', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_demand_id'), ['demand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event'), ['event'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('client_display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accidents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('occurred_time', sa.String(length=16), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('police_report_number', sa.String(length=64), nullable=True),
    sa.Column('impact_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accidents_case_id'), ['case_id'], unique=True)

    op.create_table('carriers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adjuster_name', sa.String(length=200), nullable=True),
    sa.Column('adjuster_email', sa.String(length=320), nullable=True),
    sa.Column('adjuster_phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carriers_case_id'), ['case_id'], unique=False)

    op.create_table('damage_claims',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', app.domain.money.Money(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_claims_case_id'), ['case_id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('fact_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=40), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=40), nullable=True),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_status'), ['status'], unique=False)

    op.create_table('letter_templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=400), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('structure_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('slot_names', sa.JSON(), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_case_template_sha')
    )
    with op.batch_alter_table('letter_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_letter_templates_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_letter_templates_sha256'), ['sha256'], unique=False)

    op.create_table('medical_providers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_providers_case_id'), ['case_id'], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_case_id'), ['case_id'], unique=False)

    op.create_table('settlement_terms',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('demand_type', sa.String(length=64), nullable=False),
    sa.Column('demand_amount', app.domain.money.Money(length=32), nullable=True),
    sa.Column('demand_is_policy_limits', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_method', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_terms_case_id'), ['case_id'], unique=True)

    op.create_table('source_documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('original_filename', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extraction_note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_case_document_sha')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_sha256'), ['sha256'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('claim_number', sa.String(length=64), nullable=False),
    sa.Column('date_of_loss', sa.Date(), nullable=False),
    sa.Column('carrier_id', sa.String(length=40), nullable=True),
    sa.Column('policy_number', sa.String(length=64), nullable=True),
    sa.Column('policy_limit', app.domain.money.Money(length=32), nullable=True),
    sa.Column('policy_limit_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_case_id'), ['case_id'], unique=True)

    op.create_table('demands',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('letter_date', sa.Date(), nullable=False),
    sa.Column('template_version', sa.String(length=64), nullable=True),
    sa.Column('provider_name', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('docx_key', sa.String(length=400), nullable=True),
    sa.Column('docx_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_key', sa.String(length=400), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('damages_snapshot', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.String(length=40), nullable=True),
    sa.Column('template_sha256', sa.String(length=64), nullable=True),
    sa.Column('fidelity_report', sa.JSON(), nullable=True),
    sa.Column('bind_report', sa.JSON(), nullable=True),
    sa.Column('claim_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['letter_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version', name='uq_case_demand_version')
    )
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demands_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demands_template_id'), ['template_id'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_page')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    op.create_table('fact_sources',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('fact_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('quoted_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('match_kind', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_sources_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_sources_fact_id'), ['fact_id'], unique=False)

    op.create_table('future_treatments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_low', app.domain.money.Money(length=32), nullable=True),
    sa.Column('cost_high', app.domain.money.Money(length=32), nullable=True),
    sa.Column('recommended_on', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('future_treatments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_future_treatments_case_id'), ['case_id'], unique=False)

    op.create_table('imaging_findings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=True),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('body_region', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('measurement', sa.String(length=64), nullable=True),
    sa.Column('impression', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['medical_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imaging_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imaging_findings_case_id'), ['case_id'], unique=False)

    op.create_table('medical_bills',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', app.domain.money.Money(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('billed_on', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=40), nullable=True),
    sa.Column('fact_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['medical_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_bills_case_id'), ['case_id'], unique=False)

    op.create_table('party_role_assignments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('party_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('relationship_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'role', name='uq_party_role')
    )
    with op.batch_alter_table('party_role_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_role_assignments_party_id'), ['party_id'], unique=False)

    op.create_table('treatment_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_regions', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['medical_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_events_case_id'), ['case_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('plate', sa.String(length=32), nullable=True),
    sa.Column('owner_party_id', sa.String(length=40), nullable=True),
    sa.Column('driver_party_id', sa.String(length=40), nullable=True),
    sa.Column('is_client_vehicle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_case_id'), ['case_id'], unique=False)

    op.create_table('demand_sections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('demand_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('used_fact_ids', sa.JSON(), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_id', 'key', name='uq_demand_section_key')
    )
    with op.batch_alter_table('demand_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_sections_demand_id'), ['demand_id'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('treatment_event_id', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('diagnosed_on', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treatment_event_id'], ['treatment_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_case_id'), ['case_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('demand_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_demand_id'), ['demand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)

    op.create_table('revision_proposals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('demand_id', sa.String(length=40), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_proposals_demand_id'), ['demand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_proposals_section_key'), ['section_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_proposals_status'), ['status'], unique=False)

    op.create_table('section_claims',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('demand_id', sa.String(length=40), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('citation_ids', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_claims_demand_id'), ['demand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_claims_section_key'), ['section_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_claims_status'), ['status'], unique=False)

    op.create_table('validation_issues',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('demand_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_issues_demand_id'), ['demand_id'], unique=False)

    op.create_table('revision_operations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('proposal_id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=16), nullable=False),
    sa.Column('paragraph_id', sa.String(length=64), nullable=False),
    sa.Column('before_text', sa.Text(), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=False),
    sa.Column('after_text', sa.Text(), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['revision_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_operations_proposal_id'), ['proposal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_operations_proposal_id'))

    op.drop_table('revision_operations')
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_issues_demand_id'))

    op.drop_table('validation_issues')
    with op.batch_alter_table('section_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_claims_status'))
        batch_op.drop_index(batch_op.f('ix_section_claims_section_key'))
        batch_op.drop_index(batch_op.f('ix_section_claims_demand_id'))

    op.drop_table('section_claims')
    with op.batch_alter_table('revision_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_revision_proposals_section_key'))
        batch_op.drop_index(batch_op.f('ix_revision_proposals_demand_id'))

    op.drop_table('revision_proposals')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_demand_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_case_id'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_case_id'))

    op.drop_table('diagnoses')
    with op.batch_alter_table('demand_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_sections_demand_id'))

    op.drop_table('demand_sections')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_case_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('treatment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_events_case_id'))

    op.drop_table('treatment_events')
    with op.batch_alter_table('party_role_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_role_assignments_party_id'))

    op.drop_table('party_role_assignments')
    with op.batch_alter_table('medical_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_bills_case_id'))

    op.drop_table('medical_bills')
    with op.batch_alter_table('imaging_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imaging_findings_case_id'))

    op.drop_table('imaging_findings')
    with op.batch_alter_table('future_treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_future_treatments_case_id'))

    op.drop_table('future_treatments')
    with op.batch_alter_table('fact_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_sources_fact_id'))
        batch_op.drop_index(batch_op.f('ix_fact_sources_document_id'))

    op.drop_table('fact_sources')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demands_template_id'))
        batch_op.drop_index(batch_op.f('ix_demands_case_id'))

    op.drop_table('demands')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_case_id'))

    op.drop_table('claims')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_source_documents_case_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('settlement_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_terms_case_id'))

    op.drop_table('settlement_terms')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_case_id'))

    op.drop_table('parties')
    with op.batch_alter_table('medical_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_providers_case_id'))

    op.drop_table('medical_providers')
    with op.batch_alter_table('letter_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_letter_templates_sha256'))
        batch_op.drop_index(batch_op.f('ix_letter_templates_case_id'))

    op.drop_table('letter_templates')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_status'))
        batch_op.drop_index(batch_op.f('ix_facts_case_id'))

    op.drop_table('facts')
    with op.batch_alter_table('damage_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_claims_case_id'))

    op.drop_table('damage_claims')
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carriers_case_id'))

    op.drop_table('carriers')
    with op.batch_alter_table('accidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accidents_case_id'))

    op.drop_table('accidents')
    op.drop_table('users')
    op.drop_table('cases')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event'))
        batch_op.drop_index(batch_op.f('ix_audit_events_demand_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
